# This is a basic workflow that is manually triggered

name: 01a hola mundo
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: hola mundo
        run: echo "modificando el mensaje!!"
